# Generated by Django 4.2.22 on 2025-08-03 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_booking_options_alter_cart_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='area_tag',
            field=models.CharField(blank=True, max_length=100, verbose_name='Area Tag'),
        ),
        migrations.AddField(
            model_name='item',
            name='location_tag',
            field=models.CharField(blank=True, max_length=100, verbose_name='Location Tag'),
        ),
    ]
