# Generated by Django 5.2.4 on 2025-08-16 17:11

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_item_area_tag_item_location_tag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('setting_key', models.CharField(max_length=100, unique=True, verbose_name='设置键')),
                ('setting_value', models.TextField(verbose_name='设置值')),
                ('setting_type', models.CharField(default='string', max_length=20, verbose_name='设置类型')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '租赁设置',
                'verbose_name_plural': '租赁设置',
                'ordering': ['setting_key'],
            },
        ),
        migrations.CreateModel(
            name='RentalOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
                ('duration_days', models.PositiveSmallIntegerField(verbose_name='租赁天数')),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='日租金')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='总金额')),
                ('security_deposit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='押金')),
                ('service_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='服务费')),
                ('status', models.CharField(choices=[('pending', '待确认'), ('confirmed', '已确认'), ('active', '租赁中'), ('completed', '已完成'), ('cancelled', '已取消'), ('disputed', '争议中')], default='pending', max_length=20, verbose_name='订单状态')),
                ('payment_status', models.CharField(choices=[('pending', '待付款'), ('paid', '已付款'), ('failed', '付款失败'), ('refunded', '已退款')], default='pending', max_length=20, verbose_name='付款状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='付款时间')),
                ('renter_notes', models.TextField(blank=True, verbose_name='租借者备注')),
                ('owner_notes', models.TextField(blank=True, verbose_name='所有者备注')),
                ('admin_notes', models.TextField(blank=True, verbose_name='管理员备注')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_orders', to='core.item', verbose_name='租赁物品')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_rentals_new', to=settings.AUTH_USER_MODEL, verbose_name='物品所有者')),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_orders_new', to=settings.AUTH_USER_MODEL, verbose_name='租借者')),
            ],
            options={
                'verbose_name': '租赁订单',
                'verbose_name_plural': '租赁订单',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RentalHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=100, verbose_name='操作')),
                ('description', models.TextField(verbose_name='描述')),
                ('old_status', models.CharField(blank=True, max_length=20, verbose_name='原状态')),
                ('new_status', models.CharField(blank=True, max_length=20, verbose_name='新状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='元数据')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_history', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('rental_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='rental.rentalorder', verbose_name='租赁订单')),
            ],
            options={
                'verbose_name': '租赁历史',
                'verbose_name_plural': '租赁历史',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='付款金额')),
                ('payment_method', models.CharField(choices=[('card', '信用卡/借记卡'), ('paypal', 'PayPal'), ('bank_transfer', '银行转账'), ('apple_pay', 'Apple Pay'), ('google_pay', 'Google Pay'), ('stripe', 'Stripe')], max_length=20, verbose_name='付款方式')),
                ('transaction_id', models.CharField(blank=True, max_length=255, verbose_name='交易ID')),
                ('status', models.CharField(choices=[('pending', '处理中'), ('completed', '已完成'), ('failed', '失败'), ('cancelled', '已取消'), ('refunded', '已退款')], default='pending', max_length=20, verbose_name='付款状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('payment_details', models.JSONField(blank=True, default=dict, verbose_name='付款详情')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='付款用户')),
                ('rental_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='rental.rentalorder', verbose_name='租赁订单')),
            ],
            options={
                'verbose_name': '付款记录',
                'verbose_name_plural': '付款记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='rentalorder',
            index=models.Index(fields=['status', 'start_date'], name='rental_rent_status_4d726f_idx'),
        ),
        migrations.AddIndex(
            model_name='rentalorder',
            index=models.Index(fields=['renter', 'status'], name='rental_rent_renter__d6bbce_idx'),
        ),
        migrations.AddIndex(
            model_name='rentalorder',
            index=models.Index(fields=['owner', 'status'], name='rental_rent_owner_i_4519cd_idx'),
        ),
        migrations.AddIndex(
            model_name='rentalorder',
            index=models.Index(fields=['payment_status'], name='rental_rent_payment_4f7aeb_idx'),
        ),
        migrations.AddIndex(
            model_name='rentalhistory',
            index=models.Index(fields=['rental_order', 'created_at'], name='rental_rent_rental__afe730_idx'),
        ),
        migrations.AddIndex(
            model_name='rentalhistory',
            index=models.Index(fields=['user', 'created_at'], name='rental_rent_user_id_12d399_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'created_at'], name='rental_paym_status_7e1d54_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['user', 'status'], name='rental_paym_user_id_455c7d_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['transaction_id'], name='rental_paym_transac_4a4bda_idx'),
        ),
    ]
