# Generated by Django 5.2.4 on 2025-08-16 17:51

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_item_area_tag_item_location_tag'),
        ('rental', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Payment Record', 'verbose_name_plural': 'Payment Records'},
        ),
        migrations.AlterModelOptions(
            name='rentalhistory',
            options={'ordering': ['-created_at'], 'verbose_name': 'Rental History', 'verbose_name_plural': 'Rental History'},
        ),
        migrations.AlterModelOptions(
            name='rentalorder',
            options={'ordering': ['-created_at'], 'verbose_name': 'Rental Order', 'verbose_name_plural': 'Rental Orders'},
        ),
        migrations.AlterModelOptions(
            name='rentalsettings',
            options={'ordering': ['setting_key'], 'verbose_name': 'Rental Setting', 'verbose_name_plural': 'Rental Settings'},
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Payment Amount'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Completed At'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='error_message',
            field=models.TextField(blank=True, verbose_name='Error Message'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_details',
            field=models.JSONField(blank=True, default=dict, verbose_name='Payment Details'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Credit/Debit Card'), ('paypal', 'PayPal'), ('bank_transfer', 'Bank Transfer'), ('apple_pay', 'Apple Pay'), ('google_pay', 'Google Pay'), ('stripe', 'Stripe')], max_length=20, verbose_name='Payment Method'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='rental_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='rental.rentalorder', verbose_name='Rental Order'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20, verbose_name='Payment Status'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='Transaction ID'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='Payment User'),
        ),
        migrations.AlterField(
            model_name='rentalhistory',
            name='action',
            field=models.CharField(max_length=100, verbose_name='Action'),
        ),
        migrations.AlterField(
            model_name='rentalhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='rentalhistory',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='rentalhistory',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='Metadata'),
        ),
        migrations.AlterField(
            model_name='rentalhistory',
            name='new_status',
            field=models.CharField(blank=True, max_length=20, verbose_name='New Status'),
        ),
        migrations.AlterField(
            model_name='rentalhistory',
            name='old_status',
            field=models.CharField(blank=True, max_length=20, verbose_name='Old Status'),
        ),
        migrations.AlterField(
            model_name='rentalhistory',
            name='rental_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='rental.rentalorder', verbose_name='Rental Order'),
        ),
        migrations.AlterField(
            model_name='rentalhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_history', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='rentalorder',
            name='admin_notes',
            field=models.TextField(blank=True, verbose_name='Admin Notes'),
        ),
        migrations.AlterField(
            model_name='rentalorder',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Confirmed At'),
        ),
        migrations.AlterField(
            model_name='rentalorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='rentalorder',
            name='daily_rate',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Daily Rate'),
        ),
        migrations.AlterField(
            model_name='rentalorder',
            name='duration_days',
            field=models.PositiveSmallIntegerField(verbose_name='Rental Days'),
        ),
        migrations.AlterField(
            model_name='rentalorder',
            name='end_date',
            field=models.DateField(verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='rentalorder',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_orders', to='core.item', verbose_name='Rental Item'),
        ),
        migrations.AlterField(
            model_name='rentalorder',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_rentals_new', to=settings.AUTH_USER_MODEL, verbose_name='Item Owner'),
        ),
        migrations.AlterField(
            model_name='rentalorder',
            name='owner_notes',
            field=models.TextField(blank=True, verbose_name='Owner Notes'),
        ),
        migrations.AlterField(
            model_name='rentalorder',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Payment Date'),
        ),
        migrations.AlterField(
            model_name='rentalorder',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20, verbose_name='Payment Status'),
        ),
        migrations.AlterField(
            model_name='rentalorder',
            name='renter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_orders_new', to=settings.AUTH_USER_MODEL, verbose_name='Renter'),
        ),
        migrations.AlterField(
            model_name='rentalorder',
            name='renter_notes',
            field=models.TextField(blank=True, verbose_name='Renter Notes'),
        ),
        migrations.AlterField(
            model_name='rentalorder',
            name='security_deposit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Security Deposit'),
        ),
        migrations.AlterField(
            model_name='rentalorder',
            name='service_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='Service Fee'),
        ),
        migrations.AlterField(
            model_name='rentalorder',
            name='start_date',
            field=models.DateField(verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='rentalorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('disputed', 'Disputed')], default='pending', max_length=20, verbose_name='Order Status'),
        ),
        migrations.AlterField(
            model_name='rentalorder',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Amount'),
        ),
        migrations.AlterField(
            model_name='rentalorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='rentalsettings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='rentalsettings',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='rentalsettings',
            name='setting_key',
            field=models.CharField(max_length=100, unique=True, verbose_name='Setting Key'),
        ),
        migrations.AlterField(
            model_name='rentalsettings',
            name='setting_type',
            field=models.CharField(default='string', max_length=20, verbose_name='Setting Type'),
        ),
        migrations.AlterField(
            model_name='rentalsettings',
            name='setting_value',
            field=models.TextField(verbose_name='Setting Value'),
        ),
        migrations.AlterField(
            model_name='rentalsettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
    ]
