# Generated by Django 5.2.4 on 2025-08-16 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_alter_payment_options_alter_rentalhistory_options_and_more'),
    ]

    operations = [
    ]
