# Generated by Django 5.2.4 on 2025-08-16 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_auto_20250817_0405'),
    ]

    operations = [
    ]
