# Generated by Django 5.2.4 on 2025-08-16 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0004_auto_20250817_0427'),
    ]

    operations = [
    ]
